import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import {useEffect, useState} from 'react'
import styles from '../styles/post-page.module.css'
import axios from 'axios'

const PostPage: NextPage = () => {
  const router = useRouter()
  const [postData, setPostData] = useState<any>(null)
  useEffect(() => {
    if (router.query.postId) {
        axios.get(`https://images-api.nasa.gov/search?nasa_id=${router.query.postId}`)
        .then(res => {
            if (res.data.collection.items[0].data[0].media_type == "image") {
                setPostData(res.data.collection.items[0])
            }
            else {
                router.replace("/")
            }
        }).catch((err)=>{
            router.replace("/")
        })
    }
  }, [router.query.postId])



  return (
    <div className={styles.container}>
      <Head>
        <title>Spacetagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          {postData &&
            <img src={postData.links[0].href}/>
          }
        
        
      </main>
    </div>
  )
}

export default PostPage
